# Generated by Django 4.2.19 on 2025-03-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="artworkUrl100",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="artworkUrl512",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="artworkUrl60",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="screenshotUrls",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
