# Generated by Django 4.2.19 on 2025-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_application_artworkurl100_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
